BarAndRestaurantMate/Controllers/ExpenseController.cs
using HotelMateWeb.Services.Core;
using HotelMateWeb.Services.ServiceApi;
using BarAndRestaurantMate.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;
using ClosedXML.Excel;

namespace BarAndRestaurantMate.Controllers
{
    [HandleError(View = "CustomErrorView")]
    public class ExpenseController : Controller
    {

        private readonly IPersonService _personService = null;
        private readonly IExpenseService _expenseService = null;


        public ExpenseController()
        {
            _personService = new PersonService();
            _expenseService = new ExpenseService();
        }
        public IEnumerable<ExpenseModel> GetAllItems()
        {

            return _expenseService.GetAll().Select(x => new ExpenseModel { Amount = x.Amount, Description = x.Description, ExpenseDate = x.ExpenseDate,
              ExpenseTypeId =x.ExpenseTypeId, Id = x.Id, IsActive = x.IsActive, StaffId = x.StaffId, DisplayName = x.Person.DisplayName, ExpenseTypeName = x.ExpensesType.Name} ).ToList();

            

            //using (SqlConnection myConnection = new SqlConnection(GetConnectionString()))
            //{
            //    using (SqlCommand cmd = new SqlCommand("SELECT * FROM EXPENSE", myConnection))
            //    {
            //        myConnection.Open();

            //        using (SqlDataReader dr = cmd.ExecuteReader())
            //        {
            //            while (dr.Read())
            //            {
            //                int id = dr.GetInt32(0);    // Weight int
            //                DateTime expenseDate = dr.GetDateTime(1);    // Weight int
            //                bool isActive = dr.GetBoolean(2); // Breed string 
            //                decimal amount = dr.GetDecimal(3);
            //                int staffId = dr.GetInt32(4);
            //                int expenseTypeId = dr.GetInt32(7);
            //                string description = dr.GetString(8);


            //                yield return new ExpenseModel
            //                {
            //                    Id = id,
            //                    ExpenseDate = expenseDate,
            //                    IsActive = isActive,
            //                    Amount = amount,
            //                    Description = description,
            //                    ExpenseTypeId = expenseTypeId
            //                };

            //            }
            //        }
            //    }
            //}
        }

        private static string GetConnectionString()
        {
            return ConfigurationManager.ConnectionStrings["Core"].ConnectionString;
        }

        //[OutputCache(Duration = 3600, VaryByParam = "id")]
        public ActionResult Delete(int? id)
        {
            var cats = GetAllItems();
            ExpenseModel cm = cats.FirstOrDefault(x => x.Id == id.Value);
            return View(cm);
        }

        [HttpPost]
        public ActionResult Delete(ExpenseModel cm)
        {
            int id = cm.Id;
            var cats = GetAllItems();
            var cm1 = cats.FirstOrDefault(x => x.Id == id);
            cm1.IsActive = false;
           

           

            id = UpdateItem(cm1);

            return RedirectToAction("Index");
        }

        //[OutputCache(Duration = 3600, VaryByParam = "searchText")]

        

        public void GetAllImages(string searchText)
        {

        }
    
        public ActionResult Edit(int? id, bool? saved)
        {
            var items = GetAllItems();

            var item = items.FirstOrDefault(x => x.Id == id.Value);

            int catId = item.ExpenseTypeId;

            var cats = GetAllCategories();

            var categories = cats.ToList();

            categories.Insert(0, new CategoryModel { Name = "-- Please Select--", Id = 0 });

            IEnumerable<SelectListItem> selectList =
                from c in categories
                select new SelectListItem
                {
                    Selected = (c.Id == catId),
                    Text = c.Name,
                    Value = c.Id.ToString()
                };


            ExpenseModel cm = item;

            cm.selectList = selectList;
            cm.Saved = saved;

            return View("Create", cm);
        }

        [HttpPost]
        public ActionResult Edit(ExpenseModel cm, string[] orderNumbers)
        {
            int id = 0;

            var url = string.Empty;

            var extension = string.Empty;

            var imageName = string.Empty; 


            if (ModelState.IsValid)
            {
                var username = User.Identity.Name.ToUpper();
                
                var thisUser = _personService.GetAllForLogin().Where(x => x.Username.ToUpper().Equals(username)).FirstOrDefault();
                cm.StaffId = thisUser.PersonID;


                if (cm.Id > 0)
                {
                    cm.IsActive = true;  
                    id = UpdateItem(cm);                   
                }
                else
                {
                    cm.IsActive = true;
                    cm.ExpenseDate = DateTime.Now;
                    id = InsertItem(cm);
                }

                bool saved = true;

                return RedirectToAction("Edit", new { id, saved });
            }

            int catId = cm.ExpenseTypeId;
            var cats = GetAllCategories();
            var categories = cats.ToList();

            categories.Insert(0, new CategoryModel { Name = "-- Please Select--", Id = 0 });

            IEnumerable<SelectListItem> selectList =
                from c in categories
                select new SelectListItem
                {
                    Selected = (c.Id == catId),
                    Text = c.Name,
                    Value = c.Id.ToString()
                };


            cm.selectList = selectList;

            return View(cm);
        }

        public IEnumerable<CategoryModel> GetAllCategories()
        {
            List<CategoryModel> lst = new List<CategoryModel>();

            using (SqlConnection myConnection = new SqlConnection(GetConnectionString()))
            {
                using (SqlCommand cmd = new SqlCommand("SELECT * FROM EXPENSESTYPE", myConnection))
                {
                    //cmd.CommandType = CommandType.StoredProcedure;
                    myConnection.Open();

                    //SqlParameter custId = cmd.Parameters.AddWithValue("@CustomerId", 10);

                    using (SqlDataReader dr = cmd.ExecuteReader())
                    {
                        while (dr.Read())
                        {
                            int id = dr.GetInt32(0);    // Weight int
                            string name = dr.GetString(1); // Breed string 
                            string description = dr.GetString(3);  // Name string                           
                            bool isActive = dr.GetBoolean(2); // Breed string 
                            yield return new CategoryModel { Id = id, Description = description, IsActive = isActive, Name = name };

                        }
                    }
                }
            }
        }

        
        public ActionResult IndexType()
        {
            var expensesTypeList = GetAllCategories();
            ExpenseIndexModel cim1 = new ExpenseIndexModel { ExpenseTypeList = expensesTypeList };
            return View(cim1);
        }

        //[OutputCache(Duration = 3600, VaryByParam = "id")]
        public ActionResult Index(int? id, DateTime? startDate, DateTime? endDate)
        {
            if (startDate.HasValue && endDate.HasValue)
            {
                if (startDate.Value == endDate.Value)
                {
                    var newDate = startDate.Value.AddDays(1);
                    endDate = new DateTime(newDate.Year, newDate.Month, newDate.Day, 0, 0, 1);
                }
            }

            if (!startDate.HasValue)
                startDate = DateTime.Now.AddMonths(-1);

            if (!endDate.HasValue)
                endDate = DateTime.Now.AddMonths(1);

            ExpenseIndexModel cim = new ExpenseIndexModel();

            cim.ReportName = "Discounts";

            if (id.HasValue)
            {
                var items = GetAllItems().Where(x => x.ExpenseDate >= startDate && x.ExpenseDate <= endDate);
                items = items.ToList();
                cim.ExpenseList = items;
                cim.FileToDownloadPath = GenerateExcelSheetExpenses(cim, cim.ReportName);
                return View("ProductAlerts", cim);
            }

            var items1 = GetAllItems().Where(x => x.ExpenseDate >= startDate && x.ExpenseDate <= endDate);
            cim.ExpenseList = items1;
            cim.FileToDownloadPath = GenerateExcelSheetExpenses(cim, cim.ReportName);
            return View(cim);
        }

       

        private string GenerateExcelSheetExpenses(ExpenseIndexModel model, string reportName)
        {
          
            DataTable dt = new DataTable();

            dt.Columns.AddRange(new DataColumn[5] {
                                new DataColumn("Date", typeof(string)),
                                new DataColumn("Description", typeof(string)),
                                new DataColumn("Staff", typeof(string)),
                                new DataColumn("Status",typeof(string)),
                                new DataColumn("Amount (NGN)",typeof(string))
            });

            int p = 1;

            foreach (var ru in model.ExpenseList.OrderByDescending(x => x.ExpenseDate))
            {

BarAndRestaurantMate/Views/Expense/Create.cshtml
@model BarAndRestaurantMate.Models.ExpenseModel


@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}




<div class="page-head">
    <h2>Expenses</h2>
    <ol class="breadcrumb">
        <li><a href="#">Home</a></li>
        <li><a href="#">Expense</a></li>
        <li class="active">Create/Edit</li>
    </ol>
</div>
<div class="cl-mcont">
    <div class="row">
        <div class="col-sm-6 col-md-6">
            <div class="block-flat">
                <div class="header">
                    <h3>Expense Create</h3>
                    @if (Model.Saved.HasValue && Model.Saved.Value)
                    {
                        <div class="alert alert-success alert-white rounded">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                            <div class="icon"><i class="fa fa-check"></i></div>
                            <strong>Success!</strong> Changes has been saved successfully!
                        </div>
                        <span>@Html.ActionLink("Create New", "Create")</span>
                    }
                </div>
                <div class="content">

                    @using (Html.BeginForm("CREATE", "Expense", FormMethod.Post, new { @class = "form-horizontal" }))
                    {
                        
                            @Html.HiddenFor(model => model.Id)
                            @Html.ValidationSummary(true)
                        
                              

        <div class="form-group">
            @Html.LabelFor(model => model.Description, new { @class = "col-sm-3 control-label" })
            <div class="col-sm-7">
                @Html.TextAreaFor(model => model.Description, new { @class = "form-control", @id = "Description", @placeholder = "Description" })
                @Html.ValidationMessageFor(model => model.Description)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Amount, new { @class = "col-sm-3 control-label" })
            <div class="col-sm-7">
                @Html.EditorFor(model => model.Amount, new { @class = "form-control", @id = "Amount", @placeholder = "Amount" })
                @Html.ValidationMessageFor(model => model.Amount)
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.ExpenseTypeId, new { @class = "col-sm-3 control-label" })
            <div class="col-sm-7">
                @Html.DropDownListFor(model => model.ExpenseTypeId, Model.selectList) <span><a class="btn btn-success" href="@Url.Action("NewExpenseType","Expense")">New Expense Type</a></span>
                @Html.ValidationMessageFor(model => model.ExpenseTypeId)
            </div>
        </div>

      

       <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    @{string stringValue = (Model.Id == 0) ? "Create" : "Update";}
                                    <button type="submit" class="btn btn-primary">@stringValue</button>
                                </div>
                            </div>

     
        
                        

                    }


                </div>
            </div>
        </div>
    </div>

</div>

BarAndRestaurantMate/Views/Expense/Edit.cshtml
@model BarAndRestaurantMate.Models.ExpenseModel

@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


<div class="page-head">
    <h2>Items</h2>
    <ol class="breadcrumb">
        <li><a href="#">Home</a></li>
        <li><a href="#">Item</a></li>
        <li class="active">Create/Edit</li>
    </ol>
</div>
<div class="cl-mcont">
    <div class="row">
        <div class="col-sm-6 col-md-6">
            <div class="block-flat">
                <div class="header">
                    <h3>Expense Create</h3>
                    @if (Model.Saved.HasValue && Model.Saved.Value)
                    {
                        <div class="alert alert-success alert-white rounded">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                            <div class="icon"><i class="fa fa-check"></i></div>
                            <strong>Success!</strong> Changes has been saved successfully!
                        </div>
                        <span>@Html.ActionLink("Create New", "Create")</span>
                    }
                </div>
                <div class="content">

                    @using (Html.BeginForm("CREATE", "Expense", FormMethod.Post, new { @class = "form-horizontal" }))
                    {

                        @Html.HiddenFor(model => model.Id)
                        @Html.ValidationSummary(true)



                        <div class="form-group">
                            @Html.LabelFor(model => model.Description, new { @class = "col-sm-3 control-label" })
                            <div class="col-sm-7">
                                @Html.EditorFor(model => model.Description, new { @class = "form-control", @id = "Description", @placeholder = "Description" })
                                @Html.ValidationMessageFor(model => model.Description)
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Amount, new { @class = "col-sm-3 control-label" })
                            <div class="col-sm-7">
                                @Html.EditorFor(model => model.Amount, new { @class = "form-control", @id = "Amount", @placeholder = "Amount" })
                                @Html.ValidationMessageFor(model => model.Amount)
                            </div>
                        </div>


                        <div class="form-group">
                            @Html.LabelFor(model => model.ExpenseTypeId, new { @class = "col-sm-3 control-label" })
                            <div class="col-sm-7">
                                @Html.DropDownListFor(model => model.ExpenseTypeId, Model.selectList)
                                @Html.ValidationMessageFor(model => model.ExpenseTypeId)
                            </div>
                        </div>



                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                @{string stringValue = (Model.Id == 0) ? "Create" : "Update";}
                                <button type="submit" class="btn btn-primary">@stringValue</button>
                            </div>
                        </div>
                        
                    }

                </div>
            </div>
        </div>
    </div>

</div>

BarAndRestaurantMate/Views/Expense/Index.cshtml
@model BarAndRestaurantMate.Models.ExpenseIndexModel

@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<script src="~/Scripts/jquery-1.10.2.js"></script>

<div class="page-head">
    <h2>Expenses</h2>
    <ol class="breadcrumb">
        <li><a href="#">Home</a></li>
        <li><a href="#">Expense</a></li>
        <li class="active">Expenses List</li>
    </ol>
</div>
<div class="cl-mcont">
    <div class="row">



        <div class="col-md-12">
            <div class="block-flat">
                <div class="header">
                    <h3>Expense</h3><span>@Html.ActionLink("Create New", "Create")</span>
                    @Html.Partial("_DateSelectorExpense", "Index")
                    @if (!string.IsNullOrEmpty(Model.FileToDownloadPath))
                    {
                        <span style="float:right;"><a class="label label-danger" href="@Url.Action("DownloadStatement", "BarReport", new { id = Model.FileToDownloadPath })"><i class="fa fa-download"></i>To Excel</a></span>
                    }
                </div>
                <div class="content">
                    <div class="table-responsive">
                        <table class="table no-border hover">
                            <thead class="no-border">
                                <tr>

                                    
                                    <th style="width:15%;"><strong>Date</strong></th>
                                    <th style="width:15%;"><strong>Description</strong></th>
                                    <th style="width:15%;"><strong>Staff</strong></th>
                                    <th style="width:15%;"><strong>Type</strong></th>
                                    <th style="width:15%;"><strong>Amount(NGN)</strong></th>
                                    <th style="width:15%;" class="text-center"><strong>Action</strong></th>
                                </tr>
                            </thead>
                            <tbody class="no-border-y">
                                @foreach (var item in Model.ExpenseList)
                                {
                                    <tr>
                                        
                                        <td>@item.ExpenseDate</td>
                                        <td>@item.Description</td>
                                        <td>@item.DisplayName</td>
                                        <td>@item.ExpenseTypeName</td>
                                        <td>@item.Amount</td>


                                        @*<td class="color-success"><div class="progress"><div class="progress-bar progress-bar-success" style="width: 40%">40%</div></div></td>*@
                                        <td class="text-center">
                                            <a class="label label-default" href="@Url.Action("Edit", "Expense", new {id = item.Id })">
                                                <i class="fa fa-pencil">Edit</i>
                                            </a> 
                                        </td>
                                    </tr>
                                }

                                <tr>
                                    <td colspan="4">@Model.ExpenseList.Sum(x => x.Amount)</td>
                                </tr>

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

BarAndRestaurantMate/Views/Expense/IndexType.cshtml
@model BarAndRestaurantMate.Models.ExpenseIndexModel

@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<script src="~/Scripts/jquery-1.10.2.js"></script>

<div class="page-head">
    <h2>Expense Type</h2>
    <ol class="breadcrumb">
        <li><a href="#">Home</a></li>
        <li><a href="#">Expense Type</a></li>
        <li class="active">Expenses Type List</li>
    </ol>
</div>
<div class="cl-mcont">
    <div class="row">



        <div class="col-md-12">
            <div class="block-flat">
                <div class="header">
                    <h3>Expense Type</h3><span>@Html.ActionLink("Create New", "NewExpenseType")</span>
                </div>
                <div class="content">
                    <div class="table-responsive">
                        <table class="table no-border hover">
                            <thead class="no-border">
                                <tr>
                                    <th style="width:15%;"><strong>Description</strong></th>
                                    <th style="width:15%;"><strong>Name</strong></th>
                                    <th style="width:15%;" class="text-center"><strong>Action</strong></th>
                                </tr>
                            </thead>
                            <tbody class="no-border-y">
                                @foreach (var item in Model.ExpenseTypeList)
                                {
                                    <tr>
                                        <td>@item.Description</td>
                                        <td>@item.Name</td>
                                        <td class="text-center">
                                            <a class="label label-default" href="@Url.Action("NewExpenseType", "Expense", new { id = item.Id })">
                                                <i class="fa fa-pencil">Edit</i>
                                            </a>
                                        </td>
                                    </tr>
                                }

                                

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

BarAndRestaurantMate/Views/Expense/NewExpenseType.cshtml
@model BarAndRestaurantMate.Models.ExpenseTypeModel


@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="page-head">
    <h2>Expenses</h2>
    <ol class="breadcrumb">
        <li><a href="#">Home</a></li>
        <li><a href="#">Expense Type</a></li>
        <li class="active">Create/Edit</li>
    </ol>
</div>
<div class="cl-mcont">
    <div class="row">
        <div class="col-sm-6 col-md-6">
            <div class="block-flat">
                <div class="header">
                    <h3>Expense Type Create</h3>
                    @if (Model.Saved.HasValue && Model.Saved.Value)
                    {
                        <div class="alert alert-success alert-white rounded">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                            <div class="icon"><i class="fa fa-check"></i></div>
                            <strong>Success!</strong> Changes has been saved successfully!
                        </div>
                        <span>@Html.ActionLink("Create New", "NewExpenseType")</span>
                    }
                </div>
                <div class="content">

                    @using (Html.BeginForm("NewExpenseType", "Expense", FormMethod.Post, new { @class = "form-horizontal" }))
                    {

                        @Html.HiddenFor(model => model.Id)
                        @Html.ValidationSummary()


                        <div class="form-group">
                            @Html.LabelFor(model => model.Name, new { @class = "col-sm-3 control-label" })
                            <div class="col-sm-7">
                                @Html.EditorFor(model => model.Name, new { @class = "form-control", @id = "Name", @placeholder = "Name" })
                                @Html.ValidationMessageFor(model => model.Name)
                            </div>
                        </div>



                        <div class="form-group">
                            @Html.LabelFor(model => model.Description, new { @class = "col-sm-3 control-label" })
                            <div class="col-sm-7">
                                @Html.TextAreaFor(model => model.Description, new { @class = "form-control", @id = "Description", @placeholder = "Description" })
                                @Html.ValidationMessageFor(model => model.Description)
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                @{string stringValue = (Model.Id == 0) ? "Create" : "Update";}
                                <button type="submit" class="btn btn-primary">@stringValue</button>
                            </div>
                        </div>

                  }


                </div>
            </div>
        </div>
    </div>

</div>