BarAndRestaurantMate/Controllers/GuestAccountController.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Configuration;
using System.Globalization;
using System.Linq;
using System.Web.Mvc;
using System.Web.Routing;
using HotelMateWeb.Dal.DataCore;
using HotelMateWeb.Services.Core;
using HotelMateWeb.Services.ServiceApi;
using BarAndRestaurantMate.Helpers;
using BarAndRestaurantMate.Helpers.Enums;
using BarAndRestaurantMate.Models;
using AutoMapper;
using System.IO;
using System.Drawing;
using System.Web;


namespace BarAndRestaurantMate.Controllers
{
    [Authorize()]
    [HandleError(View = "CustomErrorView")]
    public class GuestAccountController : Controller
    {
        private readonly IGuestService _guestService;
        private readonly IRoomService _roomService;
        private readonly IGuestRoomService _guestRoomService;
        private readonly IGuestReservationService _guestReservationService;
        private readonly IGuestRoomAccountService _guestRoomAccountService;
        private readonly int _hotelAccountsTime = 14;
        private readonly IBusinessAccountService _businessAccountService;

        private readonly IPersonService _personService = null;
        private readonly IGuestCredentialService _guestCredentialService = null;

        private readonly IPersonTypeService _personTypeService = null;
        private readonly IPaymentMethodService _paymentMethodService = null;
        private readonly ISupplierService _supplierService = null;
        private readonly IDistributionPointService _distributionPointService = null;



        private int? _hotelId;
        private int HotelID
        {
            get { return _hotelId ?? GetHotelId(); }
            set { _hotelId = value; }
        }

        private int GetHotelId()
        {
            var username = User.Identity.Name;
            var user = _personService.GetAllForLogin().FirstOrDefault(x => x.Username.Equals(username, StringComparison.CurrentCultureIgnoreCase));
            return user.HotelId;
        }

        public GuestAccountController()
        {
            int.TryParse(ConfigurationManager.AppSettings["HotelAccountsTime"].ToString(CultureInfo.InvariantCulture), out _hotelAccountsTime);
            _guestService = new GuestService();
            _businessAccountService = new BusinessAccountService();
            _roomService = new RoomService();
            _guestRoomService = new GuestRoomService();
            _guestReservationService = new GuestReservationService();
            _guestRoomAccountService = new GuestRoomAccountService();
            _personService = new PersonService();
            _personTypeService = new PersonTypeService();
            _paymentMethodService = new PaymentMethodService();
            _supplierService = new SupplierService();
            _guestCredentialService = new GuestCredentialService();
            _distributionPointService = new DistributionPointService();
        }

        [HttpPost]
        public ActionResult GrantInternetAccess(PersonViewModel model)
        {
            var guest = _guestService.GetById(model.GuestId);

            if(!string.IsNullOrEmpty(model.Email))
            {
                var existingPerson = _personService.GetAll(HotelID).FirstOrDefault(x => x.Username.Equals(model.Email, StringComparison.InvariantCultureIgnoreCase));
                if(model.PersonID == 0 && existingPerson != null)
                    ModelState.AddModelError("Email", "This username already exists, please enter a different username");
                if(model.PersonID > 0 && existingPerson != null)
                {
                    if(model.PersonID != existingPerson.PersonID)
                        ModelState.AddModelError("Email", "This username already exists, please enter a different username");
                }
            }

            if (ModelState.IsValid)
            {
                Mapper.CreateMap<PersonViewModel, Person>();
                Person person = Mapper.Map<PersonViewModel, Person>(model);
                //var person = guest.Person;
                
                if (model.PersonID == 0)
                {                    
                    person.HotelId = HotelID;
                    person.Address = guest.Address;
                    person.BirthDate = DateTime.Now;
                    person.DisplayName = guest.FullName;
                    person.Email = model.Email;
                    person.FirstName = guest.FullName;                    
                    person.LastName = guest.FullName;
                    person.MiddleName = guest.FullName;
                    person.Password = model.Password;
                    person.Username = model.Email;
                    person.Title = "Mr";
                    person.PersonTypeId = (int)PersonTypeEnum.Guest;
                    person.IsActive = true;
                    person.EndDate = DateTime.Now.AddYears(1);
                    person.IdNumber = model.GuestId.ToString();
                    person.PreviousEmployerStartDate = DateTime.Now;
                    person.PreviousEmployerEndDate = DateTime.Now;
                    person.StartDate = DateTime.Now;
                    guest.Person = person;
                    
                    _guestService.Update(guest);

                     //UnitOfWork unitOfWork = new UnitOfWork();

                    var currentUser = new Entitities.User();

                    currentUser.UserName = person.Username;
                    currentUser.Password = person.Password;
                    currentUser.Email = person.Email;
                    currentUser.CreatedBy = "SA";
                    currentUser.CreatedDate = DateTime.Now;
                    currentUser.CurrentStake = 0;
                    currentUser.CurrentUser = false;
                    currentUser.ForfitChanceToPlay = true;
                    currentUser.GameName = string.Empty;
                    currentUser.IsActive = true;
                    currentUser.IsComputer = false;
                    currentUser.IsGameController = false;
                    currentUser.LastLoggedInDate = DateTime.Now;
                    currentUser.LoosingMessage = string.Empty;
                    currentUser.Male = true;
                    currentUser.ModifiedDate = DateTime.Now;
                    currentUser.ModifiedBy = "SA";
                    currentUser.PlayBalance = 10000;
                    currentUser.playingNow = false;
                    currentUser.playingSeq = 0;
                    currentUser.PrevUserName = person.Username;
                    currentUser.RealMoneyBalance = 10000;
                    currentUser.ShowFinish = 0;
                    currentUser.StartDate = DateTime.Now;
                    currentUser.Status = "LIVE";
                    currentUser.UserBalance = 10000;
                    currentUser.UserPictureName = "user_anonymous.png";
                    currentUser.WinningMessage = string.Empty;
                    currentUser.PrevUserName = Guid.NewGuid().ToString();
                    //unitOfWork.UserRepository.Insert(currentUser);
                    //unitOfWork.Save();
                }
                else
                {
                    var existingPerson = _personService.GetById(model.PersonID);
                    existingPerson.Username = model.Email;
                    existingPerson.Password = model.Email;
                    existingPerson.Email = model.Email;
                    _personService.Update(existingPerson);
                }

                return RedirectToAction("EditInternetAccess", new { id = guest.Id, itemSaved = true });
            }

            var newguest = _guestService.GetById(model.GuestId);
            model.GuestName = newguest.FullName;
            return View(model);  
        }

        [HttpGet]
        //[OutputCache(Duration = 3600, VaryByParam = "id")]

        public ActionResult DenyInternetAccess(int? id)
        {
            var guest = _guestService.GetById(id.Value);
            var person = _personService.GetById(guest.PersonId);
            person = null;           
            guest.PersonId = 0;
            guest.PersonId = null;
            guest.Person = person;
            _guestService.Update(guest);
            return RedirectToAction("GuestCredentials");
        }

        //
        [HttpGet]
        public ActionResult NewSupplier()
        {
            Mapper.CreateMap<Supplier, PersonViewModel>();
            var pvm = Mapper.Map<Supplier, PersonViewModel>(new Supplier { Password = "PASSWORD", SupplierID = 0, StartDate = DateTime.Now, EndDate = DateTime.Now.AddMonths(1) });
            pvm.PersonTypes = GetPersonTypes(null);
            return View(pvm);
        }

        [HttpGet]
        public ActionResult NewPersonFull()
        {
            Mapper.CreateMap<Person, PersonViewModel>();
           
            var pvm = Mapper.Map<Person, PersonViewModel>(new Person
            {
                BirthDate = DateTime.Today.AddYears(-20),
                PersonID = 0,
                StartDate = DateTime.Now,
                EndDate = DateTime.Now.AddMonths(1),
               
                Title = "MM",

                PersonTypeId = (int)PersonTypeEnum.Guest
            });

            pvm.PersonTypes = GetPersonTypes(null);
            pvm.DistributionPoints = GetDistributionPoints(null);

            return View(pvm);
        }

        
        [HttpGet]
        public ActionResult NewPersonFullGC()
        {            
            Mapper.CreateMap<Person, PersonViewModel>();
            var gu = Guid.NewGuid().ToString();
            var pvm = Mapper.Map<Person, PersonViewModel>(new Person { Password = "Password", BirthDate = DateTime.Today.AddYears(-20), PersonID = 0, StartDate = DateTime.Now, EndDate = DateTime.Now.AddMonths(1), 

BarAndRestaurantMate/Views/GuestAccount/AdjustBill.cshtml
@model BarAndRestaurantMate.Models.GuestRoomAccountViewModel


@{
    ViewBag.Title = "Booking";
}

@Html.Partial("_AdjustBillDisplay")

@section SideBarBox
{
    @Html.Partial("_ElokasSidebar")
}

BarAndRestaurantMate/Views/GuestAccount/CheckOutGroupGuest.cshtml
@model BarAndRestaurantMate.Models.GroupBookingViewModel

@{
    ViewBag.Title = "Booking";
}

@Html.Partial("_RoomsDisplayGroupCheckouts")

@section SideBarBox
{
    @Html.Partial("_ElokasSidebar")
}

BarAndRestaurantMate/Views/GuestAccount/EditGuestAccount.cshtml
@model BarAndRestaurantMate.Models.GuestRoomAccountViewModel


@{
    ViewBag.Title = "Booking";
}

@Html.Partial("_EditGuestAccountDisplay")

@section SideBarBox
{
    @Html.Partial("_ElokasSidebar")
}

BarAndRestaurantMate/Views/GuestAccount/ExtendGuestStay.cshtml
@model BarAndRestaurantMate.Models.GuestRoomAccountViewModel


@{
    ViewBag.Title = "Booking";
}

@Html.Partial("_GuestStayDisplay")


@section SideBarBox
{
@Html.Partial("_ElokasSidebar")
}

BarAndRestaurantMate/Views/GuestAccount/GuestCredentials.cshtml
@model BarAndRestaurantMate.Models.SearchViewModel


@{
    ViewBag.Title = "Home Page";
}

@Html.Partial("_SearchViewGuestCredentials")

@section SideBarBox
{
    @Html.Partial("_SearchFilter")
}

@section PaginationBox
{
    @Html.Partial("_Pagination")
}

BarAndRestaurantMate/Views/GuestAccount/ManagePinCode.cshtml
@model BarAndRestaurantMate.Models.SearchViewModel


@{
    ViewBag.Title = "Home Page";
}

@Html.Partial("_SearchViewGC")

@section SideBarBox
{
    @*@Html.Partial("_SearchFilter")*@
}

@section PaginationBox
{
    @Html.Partial("_Pagination")
}

BarAndRestaurantMate/Views/GuestAccount/ManageSuppliers.cshtml
@model BarAndRestaurantMate.Models.SearchViewModel


@{
    ViewBag.Title = "Home Page";
}

@Html.Partial("_SearchViewSuppliers")

@section SideBarBox
{
    @Html.Partial("_SearchFilter")
}

@section PaginationBox
{
    @Html.Partial("_Pagination")
}

BarAndRestaurantMate/Views/GuestAccount/ManageUsers.cshtml
@model BarAndRestaurantMate.Models.SearchViewModel


@{
    ViewBag.Title = "Home Page";
}
<div>
    @Html.Partial("_SearchViewPersons")
</div>


@section SideBarBox
{
    @*@Html.Partial("_SearchFilter")*@
}

@section PaginationBox
{
    @Html.Partial("_Pagination")
}

BarAndRestaurantMate/Views/GuestAccount/NewGC.cshtml
@model BarAndRestaurantMate.Models.GCViewModel

<section id="content" class=" twelve columns">

    @if (Model.ItemSaved.HasValue && Model.ItemSaved.Value)
    {
        @Html.Partial("_EntityUpdated", "Person details updated.")
    }

    <h1 class="page-title ci-title"><span>Manage Users</span></h1>

    <article id="post-16" class="post-16 page type-page status-publish hentry entry group">

        <div class="booking-form-wrap bs bg">

            @using (Html.BeginForm("NewGuestCredential", "GuestAccount", FormMethod.Post, new { enctype = "multipart/form-data", @class = "booking-form b-form row" }))
            {
                @Html.Partial("_GuestCredential")
            }

        </div>

    </article>

</section>

BarAndRestaurantMate/Views/GuestAccount/NewPersonFull.cshtml
@model BarAndRestaurantMate.Models.PersonViewModel

@section scripts
{
    <script type="text/javascript">

    $(function ()
    {
        $("#submitEdit").click(function ()
        {
            if (confirm('Are you sure you want to delete this person ?')) 
            {
                return true;
            }
            else
            {
                return false;
            }

        });
    });

    </script>

}



<section id="content" class=" twelve columns">

    @if (Model.ItemSaved.HasValue && Model.ItemSaved.Value)
    {
        @Html.Partial("_EntityUpdated", "Person details updated.")
    }

    <h1 class="page-title ci-title"><span>Manage Users</span></h1>

    <article id="post-16" class="post-16 page type-page status-publish hentry entry group">

        <div class="booking-form-wrap bs bg">

            @using (Html.BeginForm("NewPersonFull", "GuestAccount", FormMethod.Post, new { enctype = "multipart/form-data", @class = "booking-form b-form row", }))
            {
                @Html.ValidationSummary()
                @Html.Partial("_PersonFull")
            }

        </div>

    </article>

</section>
<!-- #content -->
@section SideBarBox
    {
    @*@Html.Partial("_CheckAvailabilityNew")*@
}

BarAndRestaurantMate/Views/GuestAccount/NewPersonFullGC.cshtml
@model BarAndRestaurantMate.Models.PersonViewModel

<section id="content" class=" twelve columns">

    @if (Model.ItemSaved.HasValue && Model.ItemSaved.Value)
    {
        @Html.Partial("_EntityUpdated", "Person details updated.")
    }

    <h1 class="page-title ci-title"><span>Manage Users</span></h1>

    <article id="post-16" class="post-16 page type-page status-publish hentry entry group">

        <div class="booking-form-wrap bs bg">

            @using (Html.BeginForm("NewPersonQuickGC", "GuestAccount", FormMethod.Post, new { enctype = "multipart/form-data", @class = "booking-form b-form row" }))
            {
                @Html.Partial("_PersonFullQuickGC")
            }

        </div>

    </article>

</section>
<!-- #content -->
@section SideBarBox
    {
    @*@Html.Partial("_CheckAvailabilityNew")*@
}

BarAndRestaurantMate/Views/GuestAccount/NewSupplier.cshtml
@model BarAndRestaurantMate.Models.PersonViewModel

<section id="content" class=" eight columns">

    @if (Model.ItemSaved.HasValue && Model.ItemSaved.Value)
    {
        @Html.Partial("_EntityUpdated", "Supplier details updated.")
    }

    <h1 class="page-title ci-title"><span>Manage Suppliers</span></h1>

    <article id="post-16" class="post-16 page type-page status-publish hentry entry group">

        <div class="booking-form-wrap bs bg">

            @using (Html.BeginForm("NewSupplier", "GuestAccount", FormMethod.Post, new { enctype = "multipart/form-data", @class = "booking-form b-form row" }))
            {
                @Html.Partial("_SupplierFull")
            }

        </div>

    </article>

</section>
<!-- #content -->
@section SideBarBox
    {
    @Html.Partial("_CheckAvailabilityNew")
}

BarAndRestaurantMate/Views/GuestAccount/TopUpHalfDay.cshtml
@model BarAndRestaurantMate.Models.GuestRoomAccountViewModel


@{
    ViewBag.Title = "Booking";
}

@Html.Partial("_HalfDayDisplay")

@section SideBarBox
{
    @Html.Partial("_ElokasSidebar")
}

BarAndRestaurantMate/Views/GuestAccount/TransferGuest.cshtml
@model BarAndRestaurantMate.Models.RoomBookingViewModel

@{
    ViewBag.Title = "Booking";
}

@Html.Partial("_RoomsDisplayTransferGuest")

@section SideBarBox
{
    @Html.Partial("_CheckAvailabilityNew")
}

@section PaginationBox
{
    @Html.Partial("_Pagination")
}