BarAndRestaurantMate/Controllers/BarAdminController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web.Mvc;
using AutoMapper;
using HotelMateWeb.Dal.DataCore;
using HotelMateWeb.Services.Core;
using HotelMateWeb.Services.ServiceApi;
using BarAndRestaurantMate.Helpers;
using BarAndRestaurantMate.Helpers.Enums;
using BarAndRestaurantMate.Models;
using Microsoft.AspNet.Identity;
using DotNet.Highcharts;
using DotNet.Highcharts.Helpers;
using DotNet.Highcharts.Options;
using DotNet.Highcharts.Enums;
using System.Net.Mail;
using System.Net;

namespace BarAndRestaurantMate.Controllers
{
    [Authorize()]
    [HandleError(View = "CustomErrorView")]
    public class BarAdminController : Controller
    {
         private readonly IRoomService _roomService;
         private readonly IRoomTypeService _roomTypeService;
         private readonly IRoomStatuService _roomStatusService;
         private readonly IGuestService _guestService;
         private readonly IGuestRoomService _guestRoomService;
         private readonly IGuestReservationService _guestReservationService;
         private readonly IBusinessAccountService _businessAccountService;
         private readonly ITransactionService _transactionService;
         private readonly IGuestRoomAccountService _guestRoomAccountService;
         private readonly IPaymentService _soldItemService;

         private readonly IPersonService _personService = null;

         private int? _hotelId;
         private int HotelID
         {
             get { return _hotelId ?? GetHotelId(); }
             set { _hotelId = value; }
         }

         private int GetHotelId()
         {
             var username = User.Identity.Name;
             User.Identity.GetUserName();
             var user = _personService.GetAllForLogin().FirstOrDefault(x => x.Username.Equals(username, StringComparison.CurrentCultureIgnoreCase));
             return user.HotelId;
         }

         public void SendEmail()
         {
             MailMessage mail = new MailMessage("leboston@yahoo.com", "sendTo", "mailSubject", "mailBody");
             mail.From = new MailAddress("academyvistang@gmail.com", "HotelMate");
             mail.IsBodyHtml = true; // necessary if you're using html email
             NetworkCredential credential = new NetworkCredential("academyvistang@gmail.com", "Lauren280701");
             SmtpClient smtp = new SmtpClient("smtp.gmail.com", 587);
             smtp.EnableSsl = true;
             smtp.UseDefaultCredentials = false;
             smtp.Credentials = credential;
             smtp.Send(mail);
         }


        public BarAdminController()
        {
            _personService = new PersonService();
            _roomService = new RoomService();
            _roomTypeService = new RoomTypeService();
            _guestService = new GuestService();
            _guestRoomService = new GuestRoomService();
            _businessAccountService = new BusinessAccountService();
            _guestReservationService = new GuestReservationService();
            _transactionService = new TransactionService();
            _guestRoomAccountService = new GuestRoomAccountService();
            _roomStatusService = new RoomStatuService();
            _soldItemService = new PaymentService();
        }

        public ActionResult GetGraph()
        {
            var lst = new List<string []>();
            int daysInThisMonth = DateTime.Now.Day;
            var startOfMonth = new DateTime(DateTime.Now.Year,DateTime.Now.Month,1);
            var guestSales = _guestRoomService.GetAll(HotelID).Where(x => x.CheckinDate.IsBetween(startOfMonth, DateTime.Now));

            for(int i = 1; i <= daysInThisMonth; i++)
            {
               lst.Add(GetTodaysSales(i,guestSales));
            }
            

            return Json(lst.ToArray(),JsonRequestBehavior.AllowGet);
        }

        private string[] GetTodaysSales(int i, IEnumerable<GuestRoom> guestSales)
        {
            var dateNow = new DateTime(DateTime.Now.Year,DateTime.Now.Month,i);
            var sales = guestSales.Where(x => x.CheckinDate.Date == dateNow.Date).CreditSummation();
            return new[] { i.ToString(),sales.ToString() };
        }

        public ActionResult CategoryCreate()
        {
            //var gr = _guestRoomService.GetAll(HotelID).ToList();
            return View(new AdminViewModel {  });
        }

        //
        public ActionResult Marketing()
        {            

            var adminViewModel = new AdminViewModel();
            var startOfMonth = new DateTime(DateTime.Now.Year, DateTime.Now.Month, 1);
            var guestSales = _guestRoomService.GetAll(HotelID).Where(x => x.CheckinDate.IsBetween(startOfMonth, DateTime.Now));
            var creditSales = guestSales.CreditSummation();
            var debitSales = guestSales.DebitSummation();
            adminViewModel.ProfitSales = creditSales - debitSales;
            adminViewModel.MonthlyCreditSales = creditSales;
            adminViewModel.MonthlyDebitSales = debitSales;
            adminViewModel.NumberOfGuests = _guestService.GetAll(HotelID).Count(x => x.IsActive);
            adminViewModel.LongTermStay = guestSales.Count(x => x.GetNumberOfNights() > 7);
            adminViewModel.ShortTermStay = guestSales.Count(x => x.GetNumberOfNights() < 7);
            adminViewModel.ReservationCount = _guestReservationService.GetAll(HotelID).Count(x => x.StartDate > startOfMonth);
            adminViewModel.GuestSales = guestSales;
            var totalSales = guestSales.Sum(guestRoom => guestRoom.GuestRoomAccounts.Summation());
            var everything = guestSales.Sum(guestRoom => guestRoom.GuestRoomAccounts.Where(x => x.PaymentTypeId == (int)RoomPaymentTypeEnum.Laundry
                || x.PaymentTypeId == (int)RoomPaymentTypeEnum.Restuarant).Summation());
            adminViewModel.RoomOnlySales = totalSales - everything;

            return View(adminViewModel);
        }

        private DotNet.Highcharts.Helpers.Data GetRandom(MonthSales[] courses, int termId, ref List<MonthSales> validCourses)
        {
            List<Point> p = new List<Point>();

            if (validCourses == null)
                validCourses = new List<MonthSales>();

            var actualList = courses;

            if (termId == 1)
            {
                actualList = courses.Where(x => x.Scale < 4).ToArray();
            }
            else if (termId == 2)
            {
                actualList = courses.Where(x => x.Scale >= 4 && x.Scale <= 6).ToArray();
            }
            else if (termId == 3)
            {
                actualList = courses.Where(x => x.Scale >= 7 && x.Scale <= 9).ToArray();
            }
            else
            {
                actualList = courses.Where(x => x.Scale > 9).ToArray();
            }

            foreach (var n in actualList)
            {
                var startDate = GetStartDate(n);

                var endDate = GetEndDate(n);

                decimal? grade = decimal.Zero;

                grade = _soldItemService.GetAll().Where(x => x.PaymentDate >= startDate && x.PaymentDate <= endDate).Sum(x => x.Total);

                var actualScore = decimal.Zero;

                if (grade != null)
                    actualScore = grade.Value;

                n.Value = actualScore;
                validCourses.Add(n);
                p.Add(new Point { Y = (Number)actualScore });

                //if (actualScore > 0)
                //{
                //    n.Value = actualScore;
                //    validCourses.Add(n);
                //    p.Add(new Point { Y = (Number)actualScore });
                //}
                //else
                //{
                //    validCourses.Add(n);
                //}
            }

            return new DotNet.Highcharts.Helpers.Data(p.ToArray());
        }

        private DateTime GetEndDate(MonthSales month)
        {
            if (month.Name == "January")
                return new DateTime(DateTime.Now.Year, 1, 31);
            else if (month.Name == "February")
                return new DateTime(DateTime.Now.Year, 2, 28);
            else if (month.Name == "March")
                return new DateTime(DateTime.Now.Year, 3, 31);
            else if (month.Name == "April")
                return new DateTime(DateTime.Now.Year, 4, 30);
            else if (month.Name == "May")
                return new DateTime(DateTime.Now.Year, 5, 31);
            else if (month.Name == "June")
                return new DateTime(DateTime.Now.Year, 6, 30);
            else if (month.Name == "July")
                return new DateTime(DateTime.Now.Year, 7, 31);
            else if (month.Name == "August")
                return new DateTime(DateTime.Now.Year, 8, 31);
            else if (month.Name == "September")
                return new DateTime(DateTime.Now.Year, 9, 30);
            else if (month.Name == "October")
                return new DateTime(DateTime.Now.Year, 10, 31);
            else if (month.Name == "November")
                return new DateTime(DateTime.Now.Year, 11, 30);
            else
                return new DateTime(DateTime.Now.Year, 12, 31);
        }

        private DateTime GetStartDate(MonthSales month)
        {
            if (month.Name == "January")
                return new DateTime(DateTime.Now.Year, 1, 1);
            else if (month.Name == "February")
                return new DateTime(DateTime.Now.Year, 2, 1);
            else if (month.Name == "March")
                return new DateTime(DateTime.Now.Year, 3, 1);
            else if (month.Name == "April")
                return new DateTime(DateTime.Now.Year, 4, 1);
            else if (month.Name == "May")
                return new DateTime(DateTime.Now.Year, 5, 1);
            else if (month.Name == "June")
                return new DateTime(DateTime.Now.Year, 6, 1);
            else if (month.Name == "July")

BarAndRestaurantMate/Views/BarAdmin/CategoryCreate.cshtml
@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


<div class="page-head">
    <h2>Data Tables</h2>
    <ol class="breadcrumb">
        <li><a href="#">Home</a></li>
        <li><a href="#">Tables</a></li>
        <li class="active">DataTables</li>
    </ol>
</div>
    <div class="cl-mcont">
        <div class="row">
            <div class="col-sm-6 col-md-6">
                <div class="block-flat">
                    <div class="header">
                        <h3>Basic Form</h3>
                    </div>
                    <div class="content">
                        <form class="form-horizontal" role="form" parsley-validate novalidate>
                            <div class="form-group">
                                <label for="inputEmail3" class="col-sm-3 control-label">Email</label>
                                <div class="col-sm-7">
                                    <input type="email" required parsley-type="email" class="form-control" id="inputEmail3" placeholder="Email">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="inputPassword3" class="col-sm-3 control-label">Password</label>
                                <div class="col-sm-7">
                                    <input type="password" required class="form-control" id="inputPassword3" placeholder="Password">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="inputPassword3" class="col-sm-3 control-label">Web Site</label>
                                <div class="col-sm-7">
                                    <input type="url" required parsley-type="url" class="form-control" placeholder="URL">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-offset-3 col-sm-7">
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" name="remember_the_fallen"> Remember me
                                        </label>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-primary">Registrer</button>
                                    <button class="btn btn-default">Cancel</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

            <div class="col-sm-6 col-md-6">
                <div class="block-flat">
                    <div class="header">
                        <h3>Horizontal Form</h3>
                    </div>
                    <div class="content">
                        <form class="form-horizontal" role="form" parsley-validate novalidate>

                            <div class="form-group">
                                @Html.LabelFor(model => model.OrigPrice, new { @class = "col-sm-3 control-label" })
                                <div class="col-sm-7">
                                    @Html.EditorFor(model => model.OrigPrice, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.OrigPrice)
                                </div>
                            </div>

                            <div class="form-group">
                                <label for="inputEmail3" class="col-sm-3 control-label">Email</label>
                                <div class="col-sm-7">
                                    <input type="email" required parsley-type="email" class="form-control" id="inputEmail3" placeholder="Email">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="inputPassword3" class="col-sm-3 control-label">Password</label>
                                <div class="col-sm-7">
                                    <input type="password" required class="form-control" id="inputPassword3" placeholder="Password">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="inputPassword3" class="col-sm-3 control-label">Web Site</label>
                                <div class="col-sm-7">
                                    <input type="url" required parsley-type="url" class="form-control" placeholder="URL">
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-offset-3 col-sm-7">
                                    <div class="checkbox">
                                        <label>
                                            <input type="checkbox" name="remember_the_fallen"> Remember me
                                        </label>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                    <button type="submit" class="btn btn-primary">Registrer</button>
                                    <button class="btn btn-default">Cancel</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        

    </div>

BarAndRestaurantMate/Views/BarAdmin/Index.cshtml
@model BarAndRestaurantMate.Models.AdminViewModel
@using BarAndRestaurantMate.Helpers.Enums

@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

@*<script src="~/Scripts/jquery-1.10.2.js"></script>*@
<script src="~/Scripts/jquery-1.7.1.js"></script>
<script src="@Url.Content("~/Scripts/Highcharts-2.1.9/js/highcharts.src.js")" type="text/javascript"></script>


<div class="cl-mcont">

    @Html.Partial("_PieWithLegend", Model.ColumnLineAndPie)
</div>

<script type="text/javascript">
    function TooltipFormatter()
    {
        return '<b>' + this.x + '</b><br/>' +
             'Sales: ' + Highcharts.numberFormat(this.y, 1) +
             ' NGN';
    }
</script>

BarAndRestaurantMate/Views/BarAdmin/Marketing.cshtml
@model BarAndRestaurantMate.Models.AdminViewModel
@using BarAndRestaurantMate.Helpers.Enums

@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}



<div class="cl-mcont">

    <div class="stats_bar">
        <div class="butpro butstyle">
            <div class="sub"><h2>Guests</h2><span id="total_clientes">@Model.NumberOfGuests</span></div>
            <div class="stat"><span class="spk1"><canvas style="display: inline-block; width: 74px; height: 16px; vertical-align: top;" width="74" height="16"></canvas></span></div>
        </div>
        <div class="butpro butstyle">
            <div class="sub"><h2>Sales (NGN)</h2><span>@Model.MonthlyCreditSales</span></div>
            <div class="stat"><span class="up"> 13,5%</span></div>
        </div>
        <div class="butpro butstyle">
            <div class="sub"><h2>Long Stay</h2><span>@Model.LongTermStay</span></div>
            <div class="stat"><span class="down"> 20,7%</span></div>
        </div>
        <div class="butpro butstyle">
            <div class="sub"><h2>Short Stay</h2><span>@Model.ShortTermStay</span></div>
            <div class="stat"><span class="equal"> 0%</span></div>
        </div>
        <div class="butpro butstyle">
            <div class="sub"><h2>AVERAGE</h2><span>3%</span></div>
            <div class="stat"><span class="spk2"></span></div>
        </div>
        <div class="butpro butstyle">
            <div class="sub"><h2>Reservations</h2><span>@Model.ReservationCount</span></div>
            <div class="stat"><span class="spk3"></span></div>
        </div>
    </div>



</div>

BarAndRestaurantMate/Views/BarAdmin/NewCreditAccount.cshtml
@model BarAndRestaurantMate.Models.CreditAccountViewModel

<div class="row">
    <section id="content" class=" eight columns">
        <h1 class="page-title ci-title">
            <span>CREDIT ACCOUNT</span>
        </h1>

        <article id="post-16" class="post-16 page type-page status-publish hentry entry group">
            <div class="booking-form-wrap bs bg">
                @*<form class="booking-form b-form row" action="http://www.discounthotelmotels.com/preview/hotelmotel/booking/" method="post">*@
                    @using (Html.BeginForm("NewCreditAccount", "BarAdmin", FormMethod.Post, new { enctype = "multipart/form-data", @class = "booking-form b-form row" }))
                    {
                      @Html.Partial("_CreditAccount")
                    }
           </div>
        </article>


    </section> <!-- #content -->

    <div id="sidebar" class=" four columns">
            <div class="widget offer-widget bs">
                <a href="">

                    <span class="line1">SPECIAL OFFER</span>
                    <span class="line2">1 MORE DAY</span>
                    <span class="line3">FOR EVERY BOOKING IN JULY</span>

                </a>
            </div>
            <aside id="ci_galleries_widget-3" class="widget widget_ci_galleries_widget group">
                <h3 class="widget-title"><span>Latest Gallery</span></h3><div class="row">
                    <div class="twelve columns ci-gallery">
                        <div class="g-wrap bs">
                            <img width="740" height="420" src="~/images/Depositphotos_3406805_XL4-740x420.jpg" class="attachment-gallery_thumb wp-post-image" alt="Santorini beautiful volcanic island in Greece landscape with blu" />							<div class="mask">
                                <h3><a href="">The gallery</a></h3>
                                <p>A hotel is an establishment that provides lodging paid on a short-term basis. The provision of basic accommodation, in times past, consisting only of a room with a bed.</p>
                                <a class="read-more btn" href="">View Set</a>
                            </div>
                        </div>
                    </div>
                </div>
            </aside><aside id="ci_room_widget-10" class="widget widget_ci_room_widget group">
                <div class="bs entry-widget">
                    <figure>
                        <a href="">
                            <img width="740" height="420" src="~/images/Depositphotos_9500892_XL6-740x420.jpg" class="attachment-gallery_thumb wp-post-image" alt="Hotel room" />
                        </a>
                    </figure>

                    <div class="content bg">
                        <h3 class="title">Queen Suite</h3>
                        <p>A suite in a hotel or other public accommodation denotes a class of luxury accommodations, the key&hellip;</p>
                        <a class="read-more btn" href="">Read More</a>
                    </div>
                </div>
            </aside>
        </div> <!-- #sidebar -->
</div>

<div class="row">
    <div class="twelve columns">
        <div class="twelve columns main-separator"></div>
    </div>
</div>

@Html.Partial("_Widgets")
<!-- #home=widgets -->

BarAndRestaurantMate/Views/BarAdmin/NewRoom.cshtml
@model BarAndRestaurantMate.Models.RoomViewModel
           

<div class="row">
    <section id="content" class=" eight columns">
        <h1 class="page-title ci-title">
            <span>Booking</span>
        </h1>

        <article id="post-16" class="post-16 page type-page status-publish hentry entry group">

            <div class="booking-form-wrap bs bg">
                @*<form class="booking-form b-form row" action="http://www.discounthotelmotels.com/preview/hotelmotel/booking/" method="post">*@
                    @using (Html.BeginForm("NewRoom", "BarAdmin", FormMethod.Post, new { enctype = "multipart/form-data", @class = "booking-form b-form row" }))
                    {
                      @Html.Partial("_HotelRoom")
                    }
</div>

        </article>


    </section> <!-- #content -->

    <div id="sidebar" class=" four columns">
            <div class="widget offer-widget bs">
                <a href="">

                    <span class="line1">SPECIAL OFFER</span>
                    <span class="line2">1 MORE DAY</span>
                    <span class="line3">FOR EVERY BOOKING IN JULY</span>

                </a>
            </div>
            <aside id="ci_galleries_widget-3" class="widget widget_ci_galleries_widget group">
                <h3 class="widget-title"><span>Latest Gallery</span></h3><div class="row">
                    <div class="twelve columns ci-gallery">
                        <div class="g-wrap bs">
                            <img width="740" height="420" src="~/images/Depositphotos_3406805_XL4-740x420.jpg" class="attachment-gallery_thumb wp-post-image" alt="Santorini beautiful volcanic island in Greece landscape with blu" />							<div class="mask">
                                <h3><a href="">The gallery</a></h3>
                                <p>A hotel is an establishment that provides lodging paid on a short-term basis. The provision of basic accommodation, in times past, consisting only of a room with a bed.</p>
                                <a class="read-more btn" href="">View Set</a>
                            </div>
                        </div>
                    </div>
                </div>
            </aside><aside id="ci_room_widget-10" class="widget widget_ci_room_widget group">
                <div class="bs entry-widget">
                    <figure>
                        <a href="">
                            <img width="740" height="420" src="~/images/Depositphotos_9500892_XL6-740x420.jpg" class="attachment-gallery_thumb wp-post-image" alt="Hotel room" />
                        </a>
                    </figure>

                    <div class="content bg">
                        <h3 class="title">Queen Suite</h3>
                        <p>A suite in a hotel or other public accommodation denotes a class of luxury accommodations, the key&hellip;</p>
                        <a class="read-more btn" href="">Read More</a>
                    </div>
                </div>
            </aside>
        </div> <!-- #sidebar -->
</div>

<div class="row">
    <div class="twelve columns">
        <div class="twelve columns main-separator"></div>
    </div>
</div>

@Html.Partial("_Widgets")
<!-- #home=widgets -->

BarAndRestaurantMate/Views/BarAdmin/NewRoomChangeStatus.cshtml
@model BarAndRestaurantMate.Models.RoomViewModel


<div class="row">
    <section id="content" class=" eight columns">
        <h1 class="page-title ci-title">
            <span>Booking</span>
        </h1>

        <article id="post-16" class="post-16 page type-page status-publish hentry entry group">

            <div class="booking-form-wrap bs bg">
                @*<form class="booking-form b-form row" action="http://www.discounthotelmotels.com/preview/hotelmotel/booking/" method="post">*@
                @using (Html.BeginForm("NewRoom", "BarAdmin", FormMethod.Post, new { enctype = "multipart/form-data", @class = "booking-form b-form row" }))
                {
                    @Html.Partial("_HotelRoomChangeStatus")
                }
            </div>

        </article>


    </section> <!-- #content -->

    <div id="sidebar" class=" four columns">
        <div class="widget offer-widget bs">
            <a href="">

                <span class="line1">SPECIAL OFFER</span>
                <span class="line2">1 MORE DAY</span>
                <span class="line3">FOR EVERY BOOKING IN JULY</span>

            </a>
        </div>
        <aside id="ci_galleries_widget-3" class="widget widget_ci_galleries_widget group">
            <h3 class="widget-title"><span>Latest Gallery</span></h3><div class="row">
                <div class="twelve columns ci-gallery">
                    <div class="g-wrap bs">
                        <img width="740" height="420" src="~/images/Depositphotos_3406805_XL4-740x420.jpg" class="attachment-gallery_thumb wp-post-image" alt="Santorini beautiful volcanic island in Greece landscape with blu" />							<div class="mask">
                            <h3><a href="">The gallery</a></h3>
                            <p>A hotel is an establishment that provides lodging paid on a short-term basis. The provision of basic accommodation, in times past, consisting only of a room with a bed.</p>
                            <a class="read-more btn" href="">View Set</a>
                        </div>
                    </div>
                </div>
            </div>
        </aside><aside id="ci_room_widget-10" class="widget widget_ci_room_widget group">
            <div class="bs entry-widget">
                <figure>
                    <a href="">
                        <img width="740" height="420" src="~/images/Depositphotos_9500892_XL6-740x420.jpg" class="attachment-gallery_thumb wp-post-image" alt="Hotel room" />
                    </a>
                </figure>

                <div class="content bg">
                    <h3 class="title">Queen Suite</h3>
                    <p>A suite in a hotel or other public accommodation denotes a class of luxury accommodations, the key&hellip;</p>
                    <a class="read-more btn" href="">Read More</a>
                </div>
            </div>
        </aside>
    </div> <!-- #sidebar -->
</div>

<div class="row">
    <div class="twelve columns">
        <div class="twelve columns main-separator"></div>
    </div>
</div>

@Html.Partial("_Widgets")
<!-- #home=widgets -->

BarAndRestaurantMate/Views/BarAdmin/Tables.cshtml
@model BarAndRestaurantMate.Models.AdminViewModel
@using BarAndRestaurantMate.Helpers.Enums
<link href="~/Content/telerik.common.css" rel="stylesheet" />
<link href="~/Content/telerik.webblue.css" rel="stylesheet" />



@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="page-head">
    <h2>Data Tables</h2>
    <ol class="breadcrumb">
        <li><a href="#">Home</a></li>
        <li><a href="#">Tables</a></li>
        <li class="active">DataTables</li>
    </ol>
</div>
<div class="cl-mcont">

    <div class="row">
        <div class="col-md-12">
            <div class="block-flat">
                <div class="header">
                    <h3>Basic DataTable</h3>
                </div>
                <div class="content">
                    <div class="table-responsive">
                        <div class="grid_dashboard">
        @(Html.Telerik().Grid<HotelMateWeb.Dal.DataCore.GuestRoom>(Model.GuestRooms)
        .Name("Grid")
        .Columns(columns =>
        {
            columns.Template(
                    @<text>
                        @Html.ActionLink(@item.Room.RoomNumber, "Edit", new { controller = "Person", id = item.Id }, new { @class = "specialLink" })
                    </text>
               ).Width(120);
            columns.Bound(o => o.Room.RoomNumber).Title("Name").Width(130);
                
            columns.Bound(o => o.CheckinDate).Format("{0:dd/MM/yyyy}").Width(80);            
            columns.Bound(o => o.CheckoutDate).Format("{0:dd/MM/yyyy}").Width(80);
            columns.Template(
                    @<text>
                        <label> <span style="color:Red;"></span></label>
                    </text>
                                ).Title("End Date").Width(80);
      

        })
                                    .Scrollable()
                                    .Sortable()
                                    .Pageable(pager => pager.PageSize(5))
                                    .Filterable()
                            )
                            <div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>